language: python
python:
  - "pypy3"
  - "3.6"
  - "3.5"

cache: pip

env:
  global:
    - PYTEST_COMMAND="coverage run -m pytest"
  matrix:
    - TOXENV=optional
    - TOXENV=base

matrix:
  include:
    - python: "3.7"
      dist: xenial  # required for Python >= 3.7
      env: TOXENV=optional
    - python: "3.7"
      dist: xenial  # required for Python >= 3.7
      env: TOXENV=base

install:
  - pip install tox codecov

script:
  - tox

after_script:
  - python debug-info.py

after_success:
  - codecov
